### ISSUE TITLE
Radar block model isn't compiling

### ISSUE THREAD

**Issue by zrisher** [Rynchodon/Autopilot#10]
Might be a problem with my build.py run. It didn't give me any errors, but when I get in game I got this when placing a radar block:

![2015-03-19_00001](https://cloud.githubusercontent.com/assets/1958130/6727914/ecde2d5c-cde2-11e4-9732-6a61487b328d.jpg)

**Comment by Rynchodon** [comment]
F11, open in new window
What are the errors?

**Comment by zrisher** [comment]
Ah ok, got it - my mwmbuilder process was no longer running from build.py because I needed to copy `.build/build-template.ini` to `.build/build.ini` and change the program locations to match my own.

Adding a note about that to the Readme in my branch, will PR.
