### ISSUE TITLE
Radar max range is same for small and large block and doesn't match value in Radar.sbc

### ISSUE THREAD

**Issue by zrisher** [Rynchodon/Autopilot#35]
I've noticed that the max range for both the small and large radar blocks in-game is 50km, but the MaxRange value specified for the large block in AntennaRelay/Data/Radar.sbc is only 40km. Are we able to limit the range of the beacon block? If not, do you think we could manually take the maximum of set range and a default we set for each block?

I'd like the small radar block to have maybe half the range of the large? There's a few people on my server asking for that and it does seem to make sense.

**Comment by Rynchodon** [comment]
The game files do not allow for a maximum to be set, the MaxRange value was just something I forgot to delete.
I can, and have considered, forcibly limiting the range of the small radar block, but I wanted to get some feedback first. Based on the block costs and sizes I figure the small block should have 10% of the effective area of the large, which puts the power / max range around 23 km.
Another option would be to alter the formula for small radar, so that it would be less "efficient"; give away your position the same amount with less of a benefit.
Thoughts?

**Comment by zrisher** [comment]
So in-game if I turn the range on the Radar block up to max its at 50km, so 10% of that for the small block would be 5km right? Not taking into account the radar_power_c variable which basically halves its effective range. It sounds like you see max range for the big version as 230km, so I'm curious about that.

I think just less range for the small version is fine for now - we can play around with efficiency, stealth, etc when we take a pass at #16. I think 10%-30% would be fine for me. The overall max range can and should be adjusted when we work on and balance #16. 

But if we can't actually display that decreased max range in-game to the user, and they're still broadcasting their position at full range, we'll definitely need to make that clear. A lot of users have said radar shouldn't broadcast your position at all, but again I think there's some things we can implement to make that more interesting down the line.

**Comment by Rynchodon** [comment]
Max radius is currently 50 km, **volume** ~= 5.236E14
1/10th of that is 5.236E13 which gets us a max radius of ~23208 m.

Reducing the range to 5 km would make it basically useless for small objects, they could get as close as 250 m before being detected.

The ingame slider would still show the 1 m - 50 km range, but if it was set higher than the maximum we want, it would just get moved back down. I think that would make it very obvious.

> A lot of users have said radar shouldn't broadcast your position at all

* That would make radar overpowered would it not? Especially for players who are not familiar with radar in space engineers; they would just get blind-sided by players using radar.
* Being able to detect radar seems much more realistic (even if the way radar detects objects is not).
* The only way to have a 1 m - 50 km slider is for the radar to be either a beacon or a radio antenna. Making it an antenna would be a bizarrely multi-functional block.

**Comment by zrisher** [comment]
* Radius - Sorry didn't read "effective volume", totally makes sense. Yes 5km would make it difficult to pick up small objects, thinking of it from a volume perspective 20-23k makes sense to me. Perhaps a slightly larger radius for the large version makes sense eventually, or the ability to boost its power with additional dishes or components.

* Slider - awesome, glad we can visually limit that

* Broadcasting position - 
  * Unfair to unfamiliar players - Most of the people on my server pulse radar anyway, they'll turn it on for a brief second, see if anything pops up on the screen, leave it off until in the next position. Whenever someone gets found, it's "I think they were using radar", not "I saw their radar blip, dammit they're coming!". So I think the way it gets used, unfamiliar players are SOL and confused anyway. It's more of a convenience to the people using it to not keep turning it on and off, which they'd just do if they had to.
  * Unrealistic - I don't know enough about radio waves to speak well about this, but it seems more realistic to me that you'd need some sort of electromagnetic analysis program (i.e. Radar) running on your antenna's readings to tell if someone else was using radar. And then it becomes a game of counter-intelligence.
* Performance - Following up on the first point, it actually seems really advantageous to have a reason for people to turn radar off when not in use. This would be done less if you required someone had radar to detect radar. There's a linear CPU increase from having more radar detection blocks running right?

**Comment by Rynchodon** [comment]
> Unfair to unfamiliar players

I guess the way to make it noob-friendly would be to require it to stay on to function properly.
It is not much work anyway, so I will add a setting to disable broadcasting. 

> Unrealistic

You would actually need some kind of specialized detecting device, implementing this in-game is fairly complex.
In the real world there are radar detectors, radar jammers, chaff, etc. and countermeasures for all of these. I would love to implement as many of these as possible but it is a ways down the list.

> Performance

I have not clocked it but I would guess that a radar has less of a performance cost than a (dumb) turret.

**Comment by Rynchodon** [comment]
Set a minimum of 20 km for small radar & radar must stay online to be effective: f051a19af82e1599b9b4b78562d01c1193de0030

**Comment by Rynchodon** [comment]
Changes are now in master. c7d4488801ee2cba56301963214c18c2c1a89111

**Comment by zrisher** [comment]
Nice, the "charging" functionality really helps disrupt the on-off strategy.
