### ISSUE TITLE
Jump Drive

### ISSUE THREAD

**Issue by Rynchodon** [Rynchodon/Autopilot#47]
The ship powers-up for a period of time and then teleports to the destination.

In order to jump, a sufficient amount of energy needs to be stored in Jump Chargers (special batteries), the amount required is based on distance and ship mass. Jump Chargers can be charged from any power source but will only ever release energy while the ship is powering-up.

While powering-up, the chargers release energy and the drives consume it. More chargers decrease the amount of time to power-up (up to 10 chargers per drive can be used), ship mass and distance increase the time.

I was thinking that the blocks should be small and have a simple design but should look nice when stacked.

**Comment by Rynchodon** [comment]
I am considering changing the chargers to be refineries instead of batteries, so that they would play nice with power management scripts. The refineries would be inaccessible from conveyors and contain a unique material (call it jumpness) that would represent how much energy is stored within.

**Comment by Souper07** [comment]
So the system requires just one block or two? Jump chargers that store up energy (jump juice) and then an actual "jump" block that is needed to make the actual jump? Or does the Autopilot block perform the jump.

**Comment by Rynchodon** [comment]
The jump drive is a separate block, it is the only way to use up the energy from the chargers. I suppose if I switch to refineries, there could be just one block.

**Comment by Souper07** [comment]
If the chargers are not set to be batteries is there still some way to program status lights? Like how a battery has light-up textures to indicate how charged it is.

**Comment by Rynchodon** [comment]
I think the only way to have status lights is for it to be a battery.

**Comment by Souper07** [comment]
So we could have a status light that changes color depending on charge level or a sort of progression bar what fills as it charges if it is a battery. Up to you sir.

**Comment by Rynchodon** [comment]
Well I have already coded it as a battery, so that is easier for me.

**Comment by Souper07** [comment]
If it is a battery it can have status lights AND have surfaces that can be recolored by script, correct? Just browsing google, I think I found my inspiration. http://www.techpowerup.com/gpudb/images/2459.jpg
The red shapes around the edges would be the status lights, then when the charger is fully charged, the center shape would change colour to indicate the charger is full.

**Comment by zrisher** [comment]
You really don't want to go with a refinery, they contribute huge network lag even when off.

**Comment by Souper07** [comment]
Here's my first pass on the jump drive :D
![image](https://cloud.githubusercontent.com/assets/11542034/7695552/1ee1be2a-fda6-11e4-9dcf-c2e0f6a719cc.png)

**Comment by zrisher** [comment]
Lol!

**Comment by Souper07** [comment]
Sooo you can only have 4 emissive textures per battery. That graphics card design idea won't really work.

**Comment by Souper07** [comment]
Second pass:
![image](https://cloud.githubusercontent.com/assets/11542034/7720185/2da9577c-fe7f-11e4-8495-47bd53680afc.png)

The inset squares on the sides will be where the indicating lights are. The raised area on the sides next to the insets is where they keypad access terminal will be. I was thinking the square on the top could be scripted to change colors however you want. 1 block wide and about 1/2 a block tall.
Here is a SS from in game with some a basic texture slapped on it. Cargo container for size comparison.
![2015-05-19_00001](https://cloud.githubusercontent.com/assets/11542034/7720324/e458a184-fe80-11e4-94ca-2cb9cd79762e.jpg)

**Comment by zrisher** [comment]
Might just be me, but shouldn't such a powerful block be really big? Or do we rely on the battery size / amount to balance it out?

**Comment by Rynchodon** [comment]
> Might just be me, but shouldn't such a powerful block be really big? Or do we rely on the battery size / amount to balance it out?

I don't know any more! Originally I had figured that a large ship would just use a lot of batteries / chargers, but that's really not performance friendly.

I think I messed up the cost formula, unless I am reading it wrong, you would need thousands of jump chargers and hundreds of jump drives to jump the red ship...

**Comment by Souper07** [comment]
How about a nice big 3x3x3 battery.

**Comment by Souper07** [comment]
Something the same size as the radar collision box.

**Comment by Souper07** [comment]
First pass on Jump Drive. Feedback requested.
![jumpdrive](https://cloud.githubusercontent.com/assets/11542034/7791247/cdf82a2a-0251-11e5-8ea5-55479fa89f71.PNG)
![jumpdrive1](https://cloud.githubusercontent.com/assets/11542034/7791248/cfad3536-0251-11e5-953f-b3c7cad4ee9e.PNG)

**Comment by Souper07** [comment]
![capturef](https://cloud.githubusercontent.com/assets/11542034/7791538/c184750a-0256-11e5-9de0-b474ef47d9c8.PNG)
![captureasdf](https://cloud.githubusercontent.com/assets/11542034/7791539/c25cd076-0256-11e5-89f3-2c26f8ba4026.PNG)

**Comment by zrisher** [comment]
Looks amazing. Really interested to see it with textures. I feel like it should have lots of emissive lighting on those rings when running. : )

**Comment by Souper07** [comment]
![2015-06-06_00006](https://cloud.githubusercontent.com/assets/11542034/8021132/3cc82a54-0c48-11e5-91f8-0097e22353c0.jpg)
![2015-06-06_00005](https://cloud.githubusercontent.com/assets/11542034/8021133/3db21f74-0c48-11e5-8841-f0f7fc3239cc.jpg)
![2015-06-06_00004](https://cloud.githubusercontent.com/assets/11542034/8021134/3ee88ad6-0c48-11e5-8b16-d9f16446bb7c.jpg)
![2015-06-06_00002](https://cloud.githubusercontent.com/assets/11542034/8021135/40bc309c-0c48-11e5-8f1d-0d6dd932f467.jpg)
![2015-06-06_00001](https://cloud.githubusercontent.com/assets/11542034/8021137/42188616-0c48-11e5-8323-9ea9808e6986.jpg)

**Comment by Rynchodon** [comment]
Nice! What's with the radar smear?

**Comment by Souper07** [comment]
What do you mean by smear? Does the radar texture look weird to you? I'm not sure about it.

**Comment by Rynchodon** [comment]
Yeah, especially in the 2nd and 4th pictures.

**Comment by Souper07** [comment]
Here's a shot straight from the side. Think I should get rid of the radar image?
![2015-06-06_00007](https://cloud.githubusercontent.com/assets/11542034/8022762/c8bd09c6-0c9d-11e5-93b8-1d16abd8ab54.jpg)

**Comment by zrisher** [comment]
I would definitely remove the radar texture, it looks stretched and seems out of place on a jump drive block.

I would also say that there just seems to be a lot of extraneous detail - why three different green rings around the midsection? Why not just one? Why the grid pattern on the front and back of the base? Why the inwards bevel on the sides of the base? Why so many points along each ring? In general, there just seems to be a lot of detail that doesn't really help convey the functionality of the block. Brevity is the soul of wit, and that goes for visual design just as much as the written word.

**Comment by Rynchodon** [comment]
>I would definitely remove the radar texture, it looks stretched and seems out of place on a jump drive block.

I agree.

>I would also say that there just seems to be a lot of extraneous detail ... I think the fundamental pieces of this look really cool, but all the bells and whistles detract from it.

I disagree, I think the details are what really sells it and make it fit better with the blocks in S.E.

**Comment by Souper07** [comment]
Some updated SS's
![2015-06-07_00004](https://cloud.githubusercontent.com/assets/11542034/8027116/513e44e8-0d45-11e5-9232-e55c2f6f0c71.jpg)
![2015-06-07_00003](https://cloud.githubusercontent.com/assets/11542034/8027118/5143952e-0d45-11e5-9eca-fa688216102f.jpg)
![2015-06-07_00002](https://cloud.githubusercontent.com/assets/11542034/8027117/51423fb2-0d45-11e5-813f-0ab38ef503a6.jpg)

**Comment by Souper07** [comment]
Motherf***ers.

**Comment by Souper07** [comment]
Why do they keep copying us?

**Comment by zrisher** [comment]
Yep. I guess this mod just had a bunch of awesome necessary stuff. : )

**Comment by zrisher** [comment]
If only their autopilot could even compare. : /

**Comment by Souper07** [comment]
At least ours includes a small ship drive. Not sure if Ryn is going to bother finishing (starting?) these now.

**Comment by Rynchodon** [comment]
>If only their autopilot could even compare. : /

That'll be the day.

>Not sure if Ryn is going to bother finishing (starting?) these now.

Hey it's zrisher's fault! If his stupid server wouldn't crash I'd be done them by now.

I think it makes most sense for Autopilot to work with the default system, so players don't have to learn another one (and I can blame Keen when it doesn't work).

**Comment by Souper07** [comment]
I guess maybe I'll just use the models and make my own mod for the jumpdrive :/

**Comment by Souper07** [comment]
Nevermind, just got your message on Steam. I guess I'll try and do something with the models I made.

**Comment by zrisher** [comment]
> Hey it's zrisher's fault! If his stupid server wouldn't crash I'd be done them by now.

Lol sorry! We're doing a full wipe tonight, should be in a good place to give it another go soon.
