### ISSUE TITLE
Renaming Autopilot

### ISSUE THREAD

**Issue by Rynchodon** [Rynchodon/Autopilot#51]
Some suggestions:
R.A.A.T.H. Avionics
N.A.R.T.H. Avionics
Autopilot & Advance Systems
Autopilot & A.I. Ships

**Comment by zrisher** [comment]
Radar, Autopilot, Antennae communication, turret control, hyperdrive = RAATH 

Advanced Avionics
HAL 9000.  : )

**Comment by Souper07** [comment]
"Super cool awesome sauce?"

**Comment by zrisher** [comment]
Lol maybe we should do a suggestions thread on the steam mod page and then add the results to a poll?

**Comment by Rynchodon** [comment]
I'm actually going to change it this time. The change will coincide with the navigation overhaul. I'm leaning towards "Autopilot, Radar, and Military Systems"

**Comment by zrisher** [comment]
ARM? Sounds great to me. Especially if the acronym is mentioned in a couple places to help people realize there's a one-syllable word they can refer to this by.

**Comment by Souper07** [comment]
ARMS!
