### ISSUE TITLE
log rotation

### ISSUE THREAD

**Issue by zrisher** [Rynchodon/Autopilot#62]
It would be awesome if the Logger time-stamped the log files, or at least kept a few in rotation. I'm trying to debug #60 right now, but my server checks if its down and restarts every 15 min so if the crash happens close to then and I'm not fast enough, there's no way to get at the autopilot logging info.

**Comment by Rynchodon** [comment]
I don't like the idea of time-stamping them because there would be no way for Autopilot to delete them. I just figured out how to do a rotation so I should be able to implement this soon.

**Comment by zrisher** [comment]
You could also just include the timestamp in the name along with whatever other metadata you need to do the rotation right?

**Comment by Rynchodon** [comment]
Not if I ever want to be able to find the file again, file access is limited to:
* File exists
* Delete file
* Write file
* Read file

For any of these the file name must be known in advance. 

I guess it is possible to keep a master file that keeps track of log file names. This might end up being less confusing for users.

**Comment by zrisher** [comment]
I like the master file idea, I guess at first glance at that file it would be slightly more confusing, but first glance at the logs it would be significantly less. 

We could also PR a method to core that allows partial filename matches, don't know why that doesn't already exist.

Anyway, you're the one coding this up so do as you like, just my 2 cents.

**Comment by Rynchodon** [comment]
>I like the master file idea, I guess at first glance at that file it would be slightly more confusing

One option is that logs only rotate after the user creates a master file.

>We could also PR a method to core that allows partial filename matches, don't know why that doesn't already exist.

I would rather have a list files option, it would be more useful in general.

**Comment by zrisher** [comment]
Agreed, more file ops in general would be nice, shouldn't be too hard to expose since we assume a Windows file system.
