### ISSUE TITLE
guided missiles

### ISSUE THREAD

**Issue by zrisher** [Rynchodon/Autopilot#63]
It would be awesome if we had some blocks that would allow us to launch guided missiles. Looking through some real-life examples, there is a ton of complexity behind this ecosystem. There's missiles pre-guidance via GPS or Radar, in-flight guidance or lack of, [tons of types of on-missile guidance](https://en.wikipedia.org/wiki/Air-to-air_missile#Guidance) with different capabilities and weaknesses, lots of different sizes, payloads, cruising speeds, etc.

Furthermore, a lot of the real-life terminology doesn't quite apply since we're dealing with atmosphere and geographic coordinates a lot less often.

So I think we should take the most interesting parts of the current missile systems and distill them down into a simple but interesting  game system.

Here's my initial thoughts on how we could set it up:

**Guided missile launcher**
These are designed to be launched from a ship/base and destroy a fast-moving target. They are smaller and more maneuverable than ballistic missiles, with lower top speed, better acceleration, and less damage.
* Tier I - launches straight ahead but will lock onto targets within small radius from its nose, high chance to be fooled by countermeasures 
* Tier II - can launch straight ahead or be guided by radar with lock-on, larger self-guidance radius, lower chance to be fooled by countermeasures, larger damage radius
* Tier III - can launch straight ahead or be guided by radar with lock-on, faster lock-on, larger self-guidance radius, lowest chance to be fooled by countermeasures, same damage as Tier II (just better tracking)

**Guided missile (electronic) countermeasure block**
These are designed to scramble the tracking of guided missiles
Small ship and Large ship, tiers I & II

**Ballistic missile launcher**
These are designed to be launched from a ship/base and destroy a slow-moving or static high-value target a large distance away. They are larger and less maneuverable than ballistic missiles, with less acceleration and less accurate tracking, but a much higher top speed, greater damage, and immune to countermeasures (they must instead be intercepted). They do not track their targets once launched - they go to a static point determined from radar targeting. They are very expensive.
* Tier I - "Ballistic missile" - fair acceleration, high top speed, large damage radius
* Tier II - "ICBM" - lower acceleration, highest top speed, huge damage radius

**Ballistic missile interceptor launcher**
These are designed to be launched from a ship/base and destroy a very fast-moving, high-value target traveling in a predictable path (i.e. a ballistic missile). They are specially tuned to intercept ballistic missiles with a fair amount of accuracy and a large explosion radius.
* Tier I - less maneuverable than guided missile but more than ballistic, fair top speed, medium explosion radius
* Tier II - more maneuverable, faster, larger explosion radius

I think we could start with the guided missiles and countermeasures, as those will get the most use and be the easiest to balance. Then we could move on to long range ballistic missiles and their interceptors if that's even something people find valuable (it takes a looooong time to build stuff in this game right now, that much destructive potential could suck).

**Comment by Rynchodon** [comment]
Sounds good, this should be ready in a day or two?

I would recommend looking at http://danikgames.com/blog/moving-target-intercept-in-3d/ if you have not already. It's for a constant velocity projectile but since you can adjust inflight it should work.

**Comment by zrisher** [comment]
Well I was hoping the targeting could just use all the same functions already provided by radar and weapon control, with a little modification. But yes that little modification would probably end up taking a while.

**Comment by Rynchodon** [comment]
Weapon Control and Keen's turrets use the same formula, which is the link I provided. It's a bit easier to understand on danikgames.com I think.

**Comment by zrisher** [comment]
Gotcha, will check it out.

**Comment by Rynchodon** [comment]
Still working on accuracy
https://www.youtube.com/watch?v=Y2Z6q2I7-Lg

**Comment by zrisher** [comment]
That is crazy awesome. The first 30 seconds of that video is the coolest thing I've ever seen in SE modding history.

You have to post this on reddit, or let me.

**Comment by Rynchodon** [comment]
I don't have reddit but you can go ahead. I might be able to add cluster missiles too.

**Comment by zrisher** [comment]
https://www.reddit.com/r/spaceengineers/comments/3liryd/guided_missiles_coming_to_se_mods/

**Comment by zrisher** [comment]
Cluster missiles would be very cool.

I love how you explode the missile with a rock, ingenious.

**Comment by Rynchodon** [comment]
>I love how you explode the missile with a rock, ingenious.

https://www.youtube.com/watch?v=U2iiPpcwfCA

**Comment by Souper07** [comment]
Epic

**Comment by Rynchodon** [comment]
I might drop cluster missile as I am not really happy with the way they turned out. If you have any suggestions for improving them, there is a test missile in https://github.com/Rynchodon/Autopilot/tree/Guided-Missile.

**Comment by zrisher** [comment]
Cool, will check it out!

**Comment by Souper07** [comment]
Working on a launcher for the cluster missiles. 
![ffasdfsdf](https://cloud.githubusercontent.com/assets/11542034/12360490/25e6b3b2-bb6d-11e5-9c1b-2f17b2cb79d1.PNG)
![asdffffff](https://cloud.githubusercontent.com/assets/11542034/12360491/27658e48-bb6d-11e5-9bda-28df6d311f1d.PNG)

**Comment by Souper07** [comment]
![2016-01-16_00002](https://cloud.githubusercontent.com/assets/11542034/12375285/d22ffedc-bc6f-11e5-88e2-bc3985736264.jpg)
![2016-01-16_00001](https://cloud.githubusercontent.com/assets/11542034/12375286/d2e17630-bc6f-11e5-8866-259bdf456c07.jpg)

**Comment by Rynchodon** [comment]
Looking good. Could you upload what you have now so I can get started on modifying the script?

**Comment by zrisher** [comment]
These are implemented and in-game. Good job guys! Closing this issue.
