### ISSUE TITLE
Cannot place Radar block

### ISSUE THREAD

**Issue by Rynchodon** [Rynchodon/Autopilot#81]
Since the last patch, I am unable to place either type of radar block. I have tried the released version as well, to no avail. 

Is anyone else having this problem or know of what it might be?

**Comment by Souper07** [comment]
I'm having the same problem.

**Comment by Souper07** [comment]
Something to do with the mount points if I had to guess.

**Comment by zrisher** [comment]
They added the xsi type attribute to block definitions, as well as Power ResourceGroups and maybe a few other things. I had to do this to get GardenConquest blocks to place:

https://github.com/zrisher/GardenConquest/commit/7c8f84ce60a793ccb8a0736054ba0cf4a8baaeb1

**Comment by zrisher** [comment]
Here ya go, #82

**Comment by Rynchodon** [comment]
Closed by 7c540144690127797cae2a0789378912bccef326 / #82
