### ISSUE TITLE
Hacker Block

### ISSUE THREAD

**Issue by Rynchodon** [Rynchodon/Autopilot#98]
Based off the landing gear, it's a block that hacks the blocks of the ship it is attached to. A hacked  block is a temporary condition where the ownership is changed and the function is affected in some way. I plan on adding an option to E command so that it can land a hacker block or landing gear on an enemy.
The hacker gains 50 points of hackyness every 11 seconds and hacks last 17 seconds. Most hacks cost 1.

Blocks that can be hacked:
* Air vents - set to depressurize
* Doors - closed & ownership changed to hacker
* Gravity - reversed
* Turrets - disabled (costs 15)
* Turrets - turn traitor (costs 40)
* Cryo Chamber - kill player
* Jump Drive - drain power
* Medical Room - ownership changed to hacker

Other hacks that I might add:
* Connector / landing gear / merge block - disconnect
* Connector / ejector - throw out
* Thruster / Gyro - override

Thoughts? Opinions? Wild accusations?

**Comment by Souper07** [comment]
Sounds awesome.

**Comment by Souper07** [comment]
How about turning off any turrets onboard. Or maybe just disable interrior turrets or cause them to fire at players inside.

**Comment by Rynchodon** [comment]
>How about turning off any turrets onboard. Or maybe just disable interrior turrets or cause them to fire at players inside.

I could add both the option to disable turrets and to cause them to fire at allies. A different value can be assigned to these actions, so there is a choice between hijacking one turret or disabling several of them.

**Comment by Souper07** [comment]
Any idea what it should look like?

**Comment by Rynchodon** [comment]
>Any idea what it should look like?

I dunno, computerish...

**Comment by zrisher** [comment]
How about a hack defense block? Reduces amount hacked by 25 points of hackyness every 11 seconds, etc.

**Comment by Rynchodon** [comment]
>How about a hack defense block? Reduces amount hacked by 25 points of hackyness every 11 seconds, etc.

I don't think the difficulty of landing a hacker ship on a hostile one should be balanced against whether or not they built a block.

**Comment by zrisher** [comment]
Usually pretty simple to disable a turret at range and approach from the blind spot. I'm sure it'd be much more difficult if your target was online, but they rarely are. But that's probably me coming at this too much from a MP perspective.

**Comment by Rynchodon** [comment]
>Usually pretty simple to disable a turret at range and approach from the blind spot. I'm sure it'd be much more difficult if your target was online, but they rarely are. But that's probably me coming at this too much from a MP perspective.

So the player is offline, the turrets are disabled, and an enemy is boarding the ship. I don't think slowing down the hacker block is going to help much.

**Comment by zrisher** [comment]
Well offline raid defense (in any game) is all about time - they're always going to get to take maximum advantage of your weaknesses because no one's shooting at them while they think through it, but if you can make that process tricky and time-consuming it will ward off the smaller groups and hopefully give you more time to catch the larger ones in the process. But again I'm generalizing and haven't played SE in too long. As I recall, it's really easy to blow shit up. So probably not worth discussing.

**Comment by Souper07** [comment]
![concept 1 back](https://cloud.githubusercontent.com/assets/11542034/13374156/21176418-dd31-11e5-9561-db1f447a6028.PNG)
![concept 1 front](https://cloud.githubusercontent.com/assets/11542034/13374158/28bef596-dd31-11e5-82ca-90b8aea7175d.PNG)
![concept 3](https://cloud.githubusercontent.com/assets/11542034/13374159/2a1c49ac-dd31-11e5-9847-7a36e04c2225.PNG)
![concept 2](https://cloud.githubusercontent.com/assets/11542034/13374161/2b8fad9c-dd31-11e5-98f5-d248f771fec9.PNG)
![concept 1 bottom](https://cloud.githubusercontent.com/assets/11542034/13374162/2d68039e-dd31-11e5-9543-be83d1bcc91c.PNG)

**Comment by Souper07** [comment]
Going ahead with this one. The antenna things will light up when it's within range.
![concept 1 back](https://cloud.githubusercontent.com/assets/11542034/13376445/a18b6988-dd71-11e5-8b45-26162d8f4b15.PNG)
![concept 1 front](https://cloud.githubusercontent.com/assets/11542034/13376446/a373c768-dd71-11e5-9584-b74af1ee5766.PNG)

**Comment by Rynchodon** [comment]
Closed by #106 and #107
